# site settings
title: calc.ulator.world
subtitle: by Martha
email: calc@ulator.world
description: Coming soon<br /> fingers crossed.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000" 
url: "https://calc.ulator.world" # the base hostname & protocol for your site
author: Martha Laundy-Blair
formspree: xwkaydyv


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/MarthaLaundyBlair
  GitLab:
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
- svelte-components
# look back at these later for ideas
#- elements.md
- landing.md
- credits.md
- quadratic.py
